### ISSUE TITLE
Indexing raw objects

### ISSUE THREAD

**Issue by CMCDragonkai** [internalfx/mindex#8]
I have a need of storing pointers to JS objects into a collection and later being able to rapidly retrieve them. Does this deal with indexing raw JS objects that are not sorted/ordered in anyway?

Also what would be needed to make this collection system immutable, such that changes always result in a new mindex collection, rather than mutating the old one? I would prefer having some sort of builtin structure sharing rather than explicitly copying the entire mindex collection.

**Comment by internalfx** [comment]
> Does this deal with indexing raw JS objects that are not sorted/ordered in anyway?

It currently indexes strings and numbers. Typically my objects have an `id` (because they are typically database records), so I index the `id`, use mindex to find the `ids` I want, and then look them up in a dictionary.

> Also what would be needed to make this collection system immutable, such that changes always result in a new mindex collection, rather than mutating the old one? I would prefer having some sort of builtin structure sharing rather than explicitly copying the entire mindex collection.

Mindex uses standard js arrays for storage. You would probably need to use something like [immutablejs](https://github.com/facebook/immutable-js/commits/master) as the underlying storage mechanism.

**Comment by CMCDragonkai** [comment]
I found a blog talking about a fully persistent array: http://www.toves.org/books/persist/index.html#s4
